# This file configures the continuous integration (CI) system on GitHub.
# Introductory materials can be found here: https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions.
# Documentation for editing this file can be found here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Tests

# by default, give the GITHUB_TOKEN no permissions
# See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions: { }

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Code Quality
    permissions:
      # give only read-only access to the contents of the repository
      # this is the only permission this job requires, so keep it to the least privilege
      # i.e., not to issues, discussions, actions, etc.
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.14" ]
    steps:
      - uses: actions/checkout@v4

      - name: "Install uv"
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Run Ruff
        run: |
          uvx -p ${{ matrix.python-version }} ruff check
          uvx -p ${{ matrix.python-version }} ruff format --check

      - name: Run Prettier
        run: |
          npx --yes prettier --check --prose-wrap always "**/*.yml"
          npx --yes prettier --check --prose-wrap always "**/*.yaml"
          npx --yes prettier --check --prose-wrap always "**/*.md"
