version: '3.1'

services:
  instance:
    ports:
      - '127.0.0.1:${EXPOSE_PORT}:3000'
#      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: ${BUILD_ENV}
      
    # container_name: dev-frontend
    ## instead of build, specify a pre-built image:
#    image: <your-registry>/dalia/portal:latest
#    container_name: dalia-ui

# TODO should be in the same network with backend?
