#!/bin/sh
# set -e
# set -x

# # Figure out the paths based on this script’s path
# SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# FUSEKI_BASE="$(cd "$SCRIPT_DIR/.." && pwd)"
# BACKUP_SCRIPT_PATH="$FUSEKI_BASE/database/backups/tools/create_fuseki_db_backup.sh"
# JENA_TOOLS_DIR="$FUSEKI_BASE/database/backups/tools/apache-jena"
# JENA_VERSION="4.10.0"
# JENA_FILENAME="apache-jena-$JENA_VERSION.tar.gz"
# JENA_FOLDER="apache-jena-$JENA_VERSION"
# TDB2_BACKUP="$JENA_TOOLS_DIR/$JENA_FOLDER/bin/tdb2.tdbbackup"

# sudo chown -R $(id -u):$(id -g) "$FUSEKI_BASE"

# # ─── ENSURE TDB2 TOOL EXISTS ────────────────────────────────────────────────────

# if [ ! -f "$TDB2_BACKUP" ]; then
#   echo "📦 Downloading Apache Jena $JENA_VERSION CLI tools..."
#   mkdir -p "$JENA_TOOLS_DIR"
#   cd "$JENA_TOOLS_DIR" || exit 1

#   curl -fL "https://archive.apache.org/dist/jena/binaries/$JENA_FILENAME" -o "$JENA_FILENAME" || {
#     echo "❌ Failed to download Jena tools. Check version or URL."
#     exit 1
#   }

#   tar -xzf "$JENA_FILENAME"
#   chmod +x "$JENA_FOLDER/bin/"*
#   echo "✅ Tools extracted to $JENA_TOOLS_DIR"
# fi

# # ─── Create Backup Script ────────────────────────────────────────────────────

# echo "📝 Writing backup script to $BACKUP_SCRIPT_PATH..."

# cat <<EOF > "$BACKUP_SCRIPT_PATH"
# #!/bin/sh

# # ─── BACKUP FUSEKI TDB2 DATABASES ───────────────────────────────────────────────

# FUSEKI_BASE="/database"
# TDB_BACKUP="\$FUSEKI_BASE/backups/tools/apache-jena/$JENA_FOLDER/bin/tdbbackup"
# TDB2_BACKUP="\$FUSEKI_BASE/backups/tools/apache-jena/$JENA_FOLDER/bin/tdb2.tdbbackup"

# TS=\$(date +%Y%m%d_%H%M%S)
# BACKUP_ROOT="\$FUSEKI_BASE/backups/\$TS"
# mkdir -p "\$BACKUP_ROOT"

# for DB in dalia ontologies; do
#   SRC="\$FUSEKI_BASE/databases/\$DB/tdb2"
#   DST="\$BACKUP_ROOT/\$DB"
#   echo "🛟 Backing up \$DB → \$DST"
#   "\$TDB_BACKUP" "\$SRC" "\$DST"
# done

# # ─── CLEANUP: REMOVE BACKUPS OLDER THAN 30 DAYS ─────────────────────────────────

# echo "🧹 Cleaning up backups older than 30 days…"
# find "\$FUSEKI_BASE/backups" \\
#   -mindepth 1 -maxdepth 1 -type d -mtime +30 \\
#   -exec echo "→ Removing {}" \; \\
#   -exec rm -rf {} \;
# EOF

# chmod +x "$BACKUP_SCRIPT_PATH"
# echo "✅ Backup script created at: $BACKUP_SCRIPT_PATH"


##############################################################################
# 0. Resolve paths
##############################################################################
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FUSEKI_BASE="$(cd "$SCRIPT_DIR/.." && pwd)"
TOOLS_DIR="$FUSEKI_BASE/database/backups/tools"
APACHE_JENA="apache-jena"
JENA_TOOLS_DIR="$TOOLS_DIR/$APACHE_JENA"
JENA_VERSION="4.10.0"
JENA_FOLDER="apache-jena-$JENA_VERSION"
JENA_TGZ="apache-jena-$JENA_VERSION.tar.gz"
JENA_URL="https://archive.apache.org/dist/jena/binaries/$JENA_TGZ"
JENA_HOME="$JENA_TOOLS_DIR/$JENA_FOLDER"
TDB2_BACKUP="$JENA_HOME/bin/tdb2.tdbbackup"

BACKUP_SCRIPT="create_fuseki_db_backup.sh"
BACKUP_SCRIPT_PATH="$TOOLS_DIR/$BACKUP_SCRIPT"

##############################################################################
# 1. Ensure ownership (so curl/tar work even with root-owned files)
##############################################################################
sudo chown -R "$(id -u):$(id -g)" "$FUSEKI_BASE"

##############################################################################
# 2. Download Jena CLI tools if not present
##############################################################################
if [ ! -x "$TDB2_BACKUP" ]; then
  echo "📦  Downloading Apache Jena $JENA_VERSION command-line tools…"
  mkdir -p "$JENA_TOOLS_DIR" && cd "$JENA_TOOLS_DIR" || exit 1

  curl -fL "$JENA_URL" -o "$JENA_TGZ" || {
    echo "❌  Failed to download $JENA_URL"
    exit 1
  }

  tar -xzf "$JENA_TGZ"
  chmod +x "$JENA_HOME/bin/"*
  echo "✅  Extracted tools to $JENA_HOME"
fi

##############################################################################
# 3. Generate the *container-side* backup script
##############################################################################
echo "📝  Writing backup script → $BACKUP_SCRIPT_PATH"

cat <<'EOF' > "$BACKUP_SCRIPT_PATH"
#!/bin/sh
# ---------------------------------------------------------------------------
# create_fuseki_db_backup.sh
#   This script is generated by backup_db_and_data.sh
#   Runs *inside* the Fuseki container.
#   Takes live, compressed snapshots of all datasets listed in DATASETS.
#   + HTTP backups via Fuseki endpoint
#   + Poll for completion
#   + Timestamped folder + move
#   + Retention pruning
# ---------------------------------------------------------------------------

set -eu pipefail

##############################################################################
# Configuration
##############################################################################
DATASETS="dalia ontologies"        # space-separated list of dataset names
FUSEKI_BASE="/database"            # root inside the container
APACHE_JENA="apache-jena"
JENA_FOLDER="apache-jena-4.10.0"
TDB2_BACKUP="$FUSEKI_BASE/backups/tools/$APACHE_JENA/$JENA_FOLDER/bin/tdb2.tdbbackup"
RETENTION_DAYS=30

##############################################################################
# Timestamped destination root
##############################################################################
TS="backup_from_$(date '+%Y-%m-%d_%H-%M-%S')"

##############################################################################
# Ensure backup root exists and is writable by fuseki user
##############################################################################
BACKUP_ROOT="$FUSEKI_BASE/backups"
mkdir -p "$BACKUP_ROOT/$TS"
chown fuseki:fuseki "$BACKUP_ROOT"
chmod u+rwX "$BACKUP_ROOT"

chown fuseki:fuseki "$BACKUP_ROOT/$TS"
chmod u+rwX "$BACKUP_ROOT/$TS"

##############################################################################
# Backup loop: HTTP backup + TDB2 backup
##############################################################################
for DB in $DATASETS; do
  # --- 1) HTTP backup via Fuseki endpoint ---
  echo "🛰️  Starting Fuseki HTTP backup for '$DB'"
  RESP=$(curl -s -X POST http://localhost:3030/\$/backup/"$DB")
  TASK_ID=$(printf '%s' "$RESP" | sed -n 's/.*"taskId"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
  if [ -z "$TASK_ID" ]; then
    echo "❌  failed to parse taskId from: $RESP"
    continue
  fi

  # Poll until success or failure
  while :; do
    SUCCESS=$(curl -s http://localhost:3030/\$/tasks/"$TASK_ID" \
      | sed -n 's/.*"success"[[:space:]]*:[[:space:]]*\(true\|false\).*/\1/p')
    if [ "$SUCCESS" = "true" ]; then
      echo "✅  HTTP backup for '$DB' completed"
      break
    elif [ "$SUCCESS" = "false" ]; then
      echo "❌  HTTP backup for '$DB' FAILED"
      exit 1
    else
      echo "⏳  HTTP backup for '$DB' still in progress — retrying in 5s"
      sleep 5
    fi
  done

  # List all backups via HTTP
  echo "📄  Current Fuseki backups:"
  curl -s -X POST http://localhost:3030/\$/backups-list || true

  # Move the new .nq.gz backups for this DB into our timestamped folder
  BACKUPS=$(curl -s -X POST http://localhost:3030/\$/backups-list \
    | sed -n 's/.*"\([^"]*\.nq\.gz\)".*/\1/p')
  FOUND=false
  for HTTP_FILE in $BACKUPS; do
    case "$HTTP_FILE" in
      ${DB}_*.nq.gz)
        mv "$BACKUP_ROOT/$HTTP_FILE" "$BACKUP_ROOT/$TS/"
        chown fuseki:fuseki "$BACKUP_ROOT/$TS/$HTTP_FILE"
        FOUND=true
        ;;
    esac
  done
  if [ "$FOUND" != true ]; then
    echo "⚠️  no HTTP backups found for '$DB'"
  fi

  # --- 2) Local TDB2 backup (optional - requires fuseki server to be stopped) ---
  # SRC="$FUSEKI_BASE/databases/$DB/tdb2"
  # if [ ! -d "$SRC" ]; then
  #   echo "⚠️  Skipping '$DB' – directory not found: $SRC"
  #   continue
  # fi

  # DEST_DIR="$BACKUP_ROOT/$TS/$DB"
  # mkdir -p "$DEST_DIR"
  # chown fuseki:fuseki "$DEST_DIR"

  # echo "🛟  Backing up '$DB' → $DEST_DIR"
  # "$TDB2_BACKUP" --loc="$SRC"
done

##############################################################################
# Rotation – remove timestamped directories older than $RETENTION_DAYS
##############################################################################
echo "🧹  Removing backup directories older than $RETENTION_DAYS day(s)…"
find "$BACKUP_ROOT" -mindepth 1 -maxdepth 1 -type d \
     -mtime +"$RETENTION_DAYS" -exec rm -rf {} \;
echo "✅  Backup run completed."
EOF


chmod +x "$BACKUP_SCRIPT_PATH"
echo "✅  Backup script ready at $BACKUP_SCRIPT_PATH"

echo "Executing the backup script..."
podman exec -it daliaproject_dev-fuseki_1 /database/backups/tools/$BACKUP_SCRIPT
