# Generated by Django 6.0.2 on 2026-02-24 00:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token used for email confirmation link', unique=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True, help_text='When the deletion request was created')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed - Grace Period'), ('processing', 'Processing Deletion'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', help_text='Current status of the deletion request', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When user confirmed the deletion via email link', null=True)),
                ('confirmation_ip', models.GenericIPAddressField(blank=True, help_text='IP address from which confirmation was made', null=True)),
                ('confirmation_user_agent', models.TextField(blank=True, help_text='User agent string from confirmation request')),
                ('token_expires_at', models.DateTimeField(db_index=True, help_text='Token expiry (7 days from initiated_at)')),
                ('deletion_scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='When deletion will be executed (30 days from confirmed_at)', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When deletion was actually completed', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the request was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('user_snapshot', models.JSONField(default=dict, help_text='Complete snapshot of user accounts for GDPR audit trail')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Who cancelled the request (user or admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_deletions', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, help_text='Admin who executed the deletion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_deletions', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who initiated the request (self or admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_deletions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User whose account will be deleted', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Deletion Request',
                'verbose_name_plural': 'Account Deletion Requests',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountDeletionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(db_index=True, help_text="Action performed (e.g., 'request_created', 'confirmed', 'cancelled')", max_length=100)),
                ('details', models.JSONField(default=dict, help_text='Detailed information about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the actor', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this action occurred')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deletion_request', models.ForeignKey(help_text='Related deletion request', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='account_deletion.accountdeletionrequest')),
            ],
            options={
                'verbose_name': 'Deletion Audit Log',
                'verbose_name_plural': 'Deletion Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AccountDeletionItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the content object')),
                ('model_name', models.CharField(help_text='Name of the model (e.g., ResourceContent)', max_length=100)),
                ('app_label', models.CharField(default='', help_text='Django app label', max_length=100)),
                ('content_summary', models.TextField(help_text='Brief description of content for admin review')),
                ('content_data', models.JSONField(default=dict, help_text='Full snapshot of content for audit trail')),
                ('action', models.CharField(choices=[('pending', 'Pending Review'), ('delete', 'Hard Delete'), ('anonymize', 'Anonymize'), ('keep', 'Keep (Business Necessity)')], db_index=True, default='pending', help_text='Admin decision on how to handle this content', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes explaining the decision')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this item was reviewed', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When this item was actually processed', null=True)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='Type of content (model)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deletion_items', to=settings.AUTH_USER_MODEL)),
                ('deletion_request', models.ForeignKey(help_text='Parent deletion request', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='account_deletion.accountdeletionrequest')),
            ],
            options={
                'verbose_name': 'Deletion Item',
                'verbose_name_plural': 'Deletion Items',
                'ordering': ['app_label', 'model_name', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='accountdeletionrequest',
            index=models.Index(fields=['status', 'token_expires_at'], name='account_del_status_e2c64d_idx'),
        ),
        migrations.AddIndex(
            model_name='accountdeletionrequest',
            index=models.Index(fields=['status', 'deletion_scheduled_at'], name='account_del_status_bd22c0_idx'),
        ),
        migrations.AddIndex(
            model_name='accountdeletionlog',
            index=models.Index(fields=['deletion_request', 'timestamp'], name='account_del_deletio_505757_idx'),
        ),
        migrations.AddIndex(
            model_name='accountdeletionlog',
            index=models.Index(fields=['action', 'timestamp'], name='account_del_action_daae4e_idx'),
        ),
        migrations.AddIndex(
            model_name='accountdeletionitem',
            index=models.Index(fields=['deletion_request', 'action'], name='account_del_deletio_0b1d42_idx'),
        ),
        migrations.AddIndex(
            model_name='accountdeletionitem',
            index=models.Index(fields=['content_type', 'object_id'], name='account_del_content_7a7cb9_idx'),
        ),
    ]
