# Generated by Django 6.0.2 on 2026-02-25 12:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postgresql_uuid', models.UUIDField(blank=True, db_index=True, help_text='UUID4 of the entity in PostgreSQL (curation models)', null=True, unique=True)),
                ('fuseki_uuid', models.UUIDField(db_index=True, help_text='UUID4 of the entity in Fuseki graph database', unique=True)),
                ('fuseki_uri', models.URLField(db_index=True, help_text='RDF URI of the entity in Fuseki', unique=True, validators=[django.core.validators.URLValidator()])),
                ('entity_type', models.CharField(choices=[('resource', 'Resource'), ('resource_content', 'Resource Content'), ('person', 'Person'), ('organization', 'Organization'), ('license', 'License'), ('learning_resource_type', 'Learning Resource Type'), ('proficiency_level', 'Proficiency Level'), ('target_group', 'Target Group'), ('file_format', 'File Format'), ('media_type', 'Media Type'), ('language', 'Language'), ('community', 'Community'), ('relation_type', 'Relation Type'), ('relation_type_category', 'Relation Type Category')], db_index=True, help_text='Type of entity being mapped', max_length=100)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synchronized'), ('failed', 'Failed'), ('outdated', 'Outdated'), ('conflict', 'Conflict')], db_index=True, default='pending', help_text='Current synchronization status', max_length=20)),
                ('sync_direction', models.CharField(choices=[('postgresql_to_fuseki', 'PostgreSQL → Fuseki'), ('fuseki_to_postgresql', 'Fuseki → PostgreSQL'), ('bidirectional', 'Bidirectional')], default='bidirectional', help_text='Direction of synchronization', max_length=30)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Timestamp of last successful synchronization', null=True)),
                ('import_candidate', models.BooleanField(default=False, help_text='Entity exists in Fuseki but not in PostgreSQL')),
                ('import_approved', models.BooleanField(default=False, help_text='Import from Fuseki to PostgreSQL has been approved')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sync_notes', models.TextField(blank=True, help_text='Notes about synchronization status, errors, or conflicts')),
                ('fuseki_metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata from Fuseki entity (labels, descriptions, etc.)')),
                ('created_by', models.ForeignKey(help_text='User who created this mapping', on_delete=django.db.models.deletion.PROTECT, related_name='created_entity_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entity Mapping',
                'verbose_name_plural': 'Entity Mappings',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_mapping', 'Create Mapping'), ('update_mapping', 'Update Mapping'), ('sync_to_fuseki', 'Sync to Fuseki'), ('import_from_fuseki', 'Import from Fuseki'), ('bulk_operation', 'Bulk Operation'), ('conflict_resolution', 'Conflict Resolution')], max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('warning', 'Warning')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
                ('entity_mapping', models.ForeignKey(blank=True, help_text='Related entity mapping (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='entity_mapping.entitymapping')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='entitymapping',
            index=models.Index(fields=['entity_type', 'sync_status'], name='entity_mapp_entity__36e389_idx'),
        ),
        migrations.AddIndex(
            model_name='entitymapping',
            index=models.Index(fields=['import_candidate', 'import_approved'], name='entity_mapp_import__d39dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='entitymapping',
            index=models.Index(fields=['created_by', 'created'], name='entity_mapp_created_6a570e_idx'),
        ),
        migrations.AddConstraint(
            model_name='entitymapping',
            constraint=models.CheckConstraint(condition=models.Q(('postgresql_uuid__isnull', True), ('fuseki_uuid__isnull', True), _negated=True), name='at_least_one_uuid_required'),
        ),
        migrations.AddConstraint(
            model_name='entitymapping',
            constraint=models.CheckConstraint(condition=models.Q(('import_candidate', True), ('postgresql_uuid__isnull', False), _negated=True), name='import_candidates_no_postgresql_uuid'),
        ),
        migrations.AddConstraint(
            model_name='entitymapping',
            constraint=models.CheckConstraint(condition=models.Q(('sync_status', 'synced'), ('postgresql_uuid__isnull', False), ('fuseki_uuid__isnull', False), models.Q(('postgresql_uuid', models.F('fuseki_uuid')), _negated=True), _negated=True), name='synced_entities_matching_uuids'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['action', 'status'], name='entity_mapp_action_9e8ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['created_by', 'created'], name='entity_mapp_created_7f2bbd_idx'),
        ),
    ]
