# generated by datamodel-codegen:
#   filename:  index.json
#   timestamp: 2024-05-03T12:44:47+00:00

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Literal, Optional, Union


@dataclass
class PaginatedResult:
    # TODO: add validation, e.g. min_value
    count: Optional[int] = None
    offset: Optional[int] = None
    limit: Optional[int] = None


# added manually
@dataclass
class ItemSearchResult(PaginatedResult):
    results: Optional[List[Item]] = None
    facets: Optional[List[Facet]] = None


@dataclass
class ItemSearchRequest:
    query: str = field(default="*", metadata={"serializer_kwargs": {"allow_blank": True}})
    selectedFacets: List[SelectedFacet] = field(default_factory=list)
    limit: int = field(default=20, metadata={"serializer_kwargs": {"min_value": 1}})
    offset: int = field(default=0, metadata={"serializer_kwargs": {"min_value": 0}})
    sortBy: Literal["relevance", "created"] = "relevance"
    sortOrder: Literal["dsc", "asc"] = "dsc"
    datePublished_after: Optional[str] = None  # ISO date format: YYYY-MM-DD
    datePublished_before: Optional[str] = None  # ISO date format: YYYY-MM-DD


UniqueId = str
UniqueSlug = str


@dataclass
class Version:
    version_title: Optional[str] = None
    doi: Optional[str] = None
    date: Optional[str] = None


class Type(Enum):
    Event = "Event"


@dataclass
class EventSpecial:
    type: Optional[Type] = None
    start_datetime: Optional[str] = None
    end_datetime: Optional[str] = None


@dataclass
class PersonAuthor:
    firstname: Optional[str] = None  # to be deprecated
    firstName: Optional[str] = None
    lastname: Optional[str] = None  # to be deprecated
    lastName: Optional[str] = None
    orcid: Optional[str] = None

    def __post_init__(self):
        self.firstName = self.firstname
        self.lastName = self.lastname


@dataclass
class OrganizationAuthor:
    name: Optional[str] = None  # to be deprecated
    authorName: Optional[str] = None

    def __post_init__(self):
        self.authorName = self.name


@dataclass
class User:
    id: Optional[UniqueId] = None
    slug: Optional[UniqueSlug] = None
    firstname: Optional[str] = None
    lastname: Optional[str] = None
    image: Optional[str] = None
    linkedin: Optional[str] = None
    orcid: Optional[str] = None
    affiliation: Optional[str] = None
    headline: Optional[List[str]] = None
    personal_usecase: Optional[str] = None
    learning_requirements: Optional[List[str]] = None


@dataclass
class BasicSearchFilterKey:
    name: str
    label: str


@dataclass
class BasicSearchFilterValue:
    label: str
    value: str


@dataclass
class BasicSearchFilter:
    key: BasicSearchFilterKey
    values: List[BasicSearchFilterValue]


@dataclass
class License:
    # Validator complains about empty strings, see https://github.com/oxan/djangorestframework-dataclasses/issues/30
    id: Optional[str] = field(default=None, metadata={"serializer_kwargs": {"allow_blank": True}})
    name: Optional[str] = field(default=None, metadata={"serializer_kwargs": {"allow_blank": True}})
    link: Optional[str] = field(default=None, metadata={"serializer_kwargs": {"allow_blank": True}})


@dataclass
class SocialMedia:
    name: Optional[str] = None
    url: Optional[str] = None


@dataclass
class SelectedFacet:
    key: str  # facet category
    # facet items selected in the category
    selected: List[str] = field(
        metadata={"serializer_kwargs": {"child_kwargs": {"allow_blank": True}}}
    )


@dataclass
class FacetCategory:
    label: str
    name: str


@dataclass
class FacetItem:
    label: str
    value: str
    active: bool
    count: Optional[int] = None  # Number of results with this facet value


@dataclass
class Facet:
    facetCategory: Optional[FacetCategory] = None
    facetItems: Optional[List[FacetItem]] = None


@dataclass
class Error:
    message: str


@dataclass
class ResourceSpecial:
    learning_resource_types: Optional[List[LabelValueItem]] = None
    media_types: Optional[List[LabelValueItem]] = None
    disciplines: Optional[List[LabelValueItem]] = None
    target_groups: Optional[List[LabelValueItem]] = None
    proficiency_levels: Optional[List[LabelValueItem]] = None
    format: Optional[str] = None
    license: Optional[License] = None
    publication_date: Optional[str] = None
    links: Optional[List[str]] = None
    languages: Optional[List[str]] = None
    file_size: Optional[str] = None
    publisher: Optional[str] = None
    doi: Optional[str] = None
    learning_time: Optional[int] = None
    versions: Optional[List[Version]] = None


@dataclass
class Community:
    id: Optional[UniqueId] = None
    slug: Optional[UniqueSlug] = None
    title: Optional[str] = None
    image: Optional[str] = None
    url: Optional[str] = None
    social_media: Optional[List[SocialMedia]] = None
    about: Optional[str] = field(
        default=None, metadata={"serializer_kwargs": {"allow_blank": True}}
    )
    likes: Optional[int] = None
    views: Optional[int] = None
    followers: Optional[int] = None


@dataclass
class BaseItem:
    id: Optional[UniqueId] = None
    slug: Optional[UniqueSlug] = None
    title: Optional[str] = None
    communities: Optional[List[Community]] = None
    description: Optional[str] = field(
        default=None, metadata={"serializer_kwargs": {"allow_blank": True}}
    )
    authors: Optional[List[Union[PersonAuthor, OrganizationAuthor]]] = field(
        default=None,
        metadata={
            "serializer_kwargs": {"child_kwargs": {"discriminator_field_name": "authorType"}}
        },
    )
    url: Optional[str] = None
    image: Optional[str] = None
    likes: Optional[int] = None
    views: Optional[int] = None
    comments: Optional[int] = None
    tags: Optional[List[str]] = None


@dataclass
class Resource(BaseItem, ResourceSpecial):
    pass


@dataclass
class Event(BaseItem, EventSpecial):
    pass


Item = Union[Event, Resource]


@dataclass
class CurationSuggestSearchRequest:
    q: str = field(default="", metadata={"serializer_kwargs": {"allow_blank": True}})
    limit: int = field(default=10, metadata={"serializer_kwargs": {"min_value": 1}})
    offset: int = field(default=0, metadata={"serializer_kwargs": {"min_value": 0}})


@dataclass
class LabelValueItem:
    label: str
    value: str  # typically the URI of the item


@dataclass
class CurationSuggestPaginatedResult(PaginatedResult):
    results: List[LabelValueItem] = None


@dataclass
class CurationSuggestDisciplinesResultItem(LabelValueItem):
    children: List[CurationSuggestDisciplinesResultItem]


@dataclass
class CurationSuggestLicensesRequest(CurationSuggestSearchRequest):
    filter: Literal["recommended", "all", "recent"] = "all"


@dataclass
class CurationSuggestLicensesResultItem:
    value: Optional[str] = None
    licenseId: Optional[str] = None
    licenseName: Optional[str] = None
    licenseLink: Optional[str] = None
    licenseDescription: Optional[str] = None


@dataclass
class CurationSuggestLicensesResult(PaginatedResult):
    results: List[CurationSuggestLicensesResultItem] = None
