# Generated by Django 6.0.5 on 2026-05-14 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecommunityrelation',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_relations', to='curation.community'),
        ),
    ]
