# Generated by Django 6.0.5 on 2026-05-20 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0002_fix_community_relation_cascade'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecontent',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='resourcecontent',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='resourcecontent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('resource',), name='uniq_active_content_per_resource'),
        ),
    ]
