# Generated by Django 6.0.5 on 2026-05-20 14:14

from django.db import migrations


def backfill_versions_and_active(apps, schema_editor):
    Resource = apps.get_model("curation", "Resource")
    ResourceContent = apps.get_model("curation", "ResourceContent")

    for resource in Resource.objects.all():
        contents = list(
            ResourceContent.objects.filter(resource=resource).order_by("id")
        )
        if not contents:
            continue

        # Assign sequential version numbers by creation order
        for i, content in enumerate(contents, start=1):
            content.version = i
        ResourceContent.objects.bulk_update(contents, ["version"])

        # Pick the active content:
        # First choice: lowest id with submitted_for_review=False
        # Fallback: lowest id overall
        active = next(
            (c for c in contents if not c.submitted_for_review),
            contents[0],
        )
        ResourceContent.objects.filter(resource=resource).update(is_active=False)
        ResourceContent.objects.filter(pk=active.pk).update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0003_resourcecontent_is_active_resourcecontent_version_and_more"),
    ]

    operations = [
        migrations.RunPython(
            backfill_versions_and_active,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
