# Generated by Django 6.0.5 on 2026-06-02 09:59

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0004_resourcecontent_backfill_versions'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecontent',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('title', 'description', config='english'), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddIndex(
            model_name='resourcecontent',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='rc_fts_vector_gin'),
        ),
    ]
