# Generated by Django 6.0.6 on 2026-06-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0006_person_sync_name_from_provider"),
    ]

    operations = [
        # Step 1: make nullable (no unique yet — avoids constraint violation during data fix)
        migrations.AlterField(
            model_name="community",
            name="uri",
            field=models.URLField(blank=True, null=True),
        ),
        # Step 2: convert existing empty strings to NULL so unique constraint can apply
        migrations.RunSQL(
            sql="UPDATE curation_community SET uri = NULL WHERE uri = ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 3: add unique constraint
        migrations.AlterField(
            model_name="community",
            name="uri",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
