# Generated by Django 6.0.6 on 2026-06-23 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0007_community_uri_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('first_name', 'last_name'), name='unique_guest_person_name'),
        ),
    ]
