# Generated by Django 6.0.6 on 2026-06-24 06:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0008_person_unique_guest_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.URLField(blank=True, help_text='Community logo or banner image URL', null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='website_url',
            field=models.URLField(blank=True, default='', help_text='Community website URL'),
        ),
        migrations.CreateModel(
            name='CommunitySocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Platform name, e.g. Zenodo, YouTube', max_length=100)),
                ('url', models.URLField(help_text="Full URL to the community's profile on this platform")),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='curation.community')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ('name',),
            },
        ),
    ]
