# Generated by Django 6.0.2 on 2026-02-23 23:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Required. A valid email address.', max_length=254, unique=True, verbose_name='email address')),
                ('bio', models.TextField(blank=True, help_text='Brief description about the user', max_length=500, verbose_name='biography')),
                ('institution', models.CharField(blank=True, help_text='University, research institution, or organization', max_length=255, verbose_name='institution')),
                ('orcid', models.CharField(blank=True, default=None, help_text='ORCID identifier (e.g., 0000-0002-1234-5678)', max_length=19, null=True, unique=True, verbose_name='ORCID')),
                ('website', models.URLField(blank=True, help_text='Personal or professional website', verbose_name='website')),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/', verbose_name='avatar')),
                ('is_profile_public', models.BooleanField(default=True, help_text='Whether the profile is visible to other users', verbose_name='public profile')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the user account has been verified', verbose_name='verified')),
                ('last_activity', models.DateTimeField(blank=True, help_text='Last time the user was active on the platform', null=True, verbose_name='last activity')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('research_areas', models.TextField(blank=True, help_text='Comma-separated list of research areas', verbose_name='research areas')),
                ('language_preference', models.CharField(default='en', help_text='Preferred language for the interface', max_length=10, verbose_name='language preference')),
                ('timezone', models.CharField(default='UTC', help_text='User timezone', max_length=50, verbose_name='timezone')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications', verbose_name='email notifications')),
                ('newsletter_subscription', models.BooleanField(default=False, help_text='Subscribe to the newsletter', verbose_name='newsletter subscription')),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['orcid'], name='users_user_orcid_1fd3f9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['institution'], name='users_user_institu_0769e0_idx'),
        ),
    ]
