# Generated by Django 6.0.5 on 2026-05-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_orcid_1fd3f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_institu_0769e0_idx',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_profile_public',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='orcid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
    ]
