# Generated by Django 6.0.5 on 2026-05-13 19:10

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_strip_invented_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
            ],
            options={
                'verbose_name': 'User Details',
                'verbose_name_plural': 'User Details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
