# server {
#     listen 80;
#     server_name search.dalia.education; # Change localhost to search.dalia.education
#     root /usr/share/nginx/html;
#     index maintenance.html; # Set maintenance.html as the index file
# }
server {
    listen 80;
    server_name search.dalia.education;

    # Maintenance mode - redirect all requests (including query strings)
    rewrite ^(.*)$ /maintenance.html? break;

    location /maintenance.html {
        root /usr/share/nginx/html;
    }
}