# Generated by Django 6.0.5 on 2026-05-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('language', models.CharField(choices=[('de', 'German'), ('en', 'English')], max_length=2)),
                ('content_md', models.TextField(blank=True)),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='pages/docx/')),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['slug', 'language'],
                'unique_together': {('slug', 'language')},
            },
        ),
    ]
